database: cassandra

#database_env: docker
#database_config:
#  host: localhost
#  container: ivy-ui-cassandra

database_env: ssh
database_config:
  host: [192.168.2.71,192.168.2.72,192.168.2.73,192.168.2.74,192.168.2.75]
#  #post: 

