database: cassandra

#database_env: docker
#database_config:
#  host: localhost
#  container: ivy-ui-cassandra

database_env: ssh
database_config:
  host: [192.168.1.40,192.168.1.41,192.168.1.42,192.168.1.43,192.168.1.44]
#  #post: 

